services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: propertydb
      MYSQL_USER: propertyuser
      MYSQL_PASSWORD: propertypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: spring-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/propertydb
      SPRING_DATASOURCE_USERNAME: propertyuser
      SPRING_DATASOURCE_PASSWORD: propertypass
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  db_data:
